Pull Request #1 de Sprint1 BBDD
infabeti/BBDD-Arkaitz-Asier-David-Lopez-y-Unai-Garcia- pull request #1
Opened 2021-04-27 08:07 UTC by ALasherasSus

Hacemos el pull request.

2021-04-27 08:22 UTC, infabeti commented on BDD-Reto4BigData/src/main/java/principal/Consultas.java
> +public class Consultas {
Teneis que crear un sistema para que la base de datos no dependa de ningún modelo externo. Es decir, teneis que crear un metodo que reciba un statement y devuelva un result set. Y, será la aplicación la que deberá de hacer el tratamiento de ese resultado en base a su modelo.

2021-04-27 08:22 UTC, infabeti commented on BDD-Reto4BigData/src/main/java/principal/ConsultasComprobaciones.java
> +public class ConsultasComprobaciones {
+1

2021-04-27 08:22 UTC, infabeti commented on BDD-Reto4BigData/src/main/java/principal/ConsultasListas.java
> +public class ConsultasListas {
+1

2021-04-27 08:23 UTC, infabeti commented on BDD-Reto4BigData/src/main/java/principal/Inserciones.java
> +public class Inserciones {
+1

2021-04-27 08:23 UTC, infabeti commented on BDD-Reto4BigData/src/main/java/principal/InsercionesActividades.java
> +public class InsercionesActividades {
+1

2021-04-27 08:24 UTC, infabeti commented on BDD-Reto4BigData/src/main/java/principal/SentenciasBBDD.java
> +public class SentenciasBBDD {
Esto si quereis si que podeis dejarlo aquí. Aunque, tal vez sea más comodo que lo tengais en la aplicación. Es decisión vuestra.

2021-04-27 08:24 UTC, infabeti requested changes
La base de datos no tiene que tener ninguna depencia sobre el modelo. Corregidlo.

2021-04-27 10:04 UTC, Unai-GarciaGi commented on BDD-Reto4BigData/src/main/java/principal/Consultas.java
> +public class Consultas {
El código de la base de datos formatea el result set para hacer el código de la APP más sencillo, además de hacerlo así por indicaciones anteriores y falta de tiempo, pero podemos hacer esto para el sprint 2 si hace falta

2021-04-27 17:45 UTC, Jose-Elorrieta commented
El trigger ya lo teníais hecho del anterior reto y es correcto.
En cuanto al procedimiento, es correcto, pero se puede hacer alguna optimización del código. Os lo comento mañana en clase.

2021-04-28 07:33 UTC, Jose-Elorrieta commented
Tenéis mi visto bueno para la parte de BBDD.

2021-04-28 11:53 UTC, Jose-Elorrieta approved these changes

2021-04-30 21:27 UTC, Unai-GarciaGi commented on BDD-Reto4BigData/src/main/java/principal/Consultas.java
> +public class Consultas {
Cambiado, ahora en consultas solo existe un método que recibe un statement y devuelve un resultset

2021-04-30 21:27 UTC, Unai-GarciaGi commented on BDD-Reto4BigData/src/main/java/principal/ConsultasComprobaciones.java
> +public class ConsultasComprobaciones {
Eliminado, no es necesaria esa clase

2021-04-30 21:28 UTC, Unai-GarciaGi commented on BDD-Reto4BigData/src/main/java/principal/ConsultasListas.java
> +public class ConsultasListas {
Eliminado, no hace falta esa clase

2021-04-30 21:29 UTC, Unai-GarciaGi commented on BDD-Reto4BigData/src/main/java/principal/Inserciones.java
> +public class Inserciones {
Cambiado, ahora inserciones tiene únicamente un método que recibe un statement y no devuelve nada, ya que las inserciones no devuelven, y otro que ejecuta la función de la base de datos. Consideramos que esto último debe estar aquí ya que no depende del modelo

2021-04-30 21:29 UTC, Unai-GarciaGi commented on BDD-Reto4BigData/src/main/java/principal/InsercionesActividades.java
> +public class InsercionesActividades {
Clase eliminada, no hace falta

2021-04-30 21:29 UTC, Unai-GarciaGi commented on BDD-Reto4BigData/src/main/java/principal/SentenciasBBDD.java
> +public class SentenciasBBDD {
Hemos decidido dejarla, pero ahora todos los strings son public para poder utilizarlos desde el modelo

2021-05-02 17:24 UTC, infabeti approved these changes

2021-05-02 17:24 UTC, merged