Sprint2
infabeti/BBDD-Arkaitz-Asier-David-Lopez-y-Unai-Garcia- pull request #2
Opened 2021-05-12 07:52 UTC by Asierhernandezga

Hemos terminado el sprint 2 de la BBDD, hacemos el pull request

2021-05-12 21:01 UTC, Jose-Elorrieta requested changes
¡Muy buen trabajo! 
Los procedimientos creados son correctos.
El diagrama E-R y el script de creación de la BD con las nuevas tablas también son correctos. Sin embargo, en el esquema relacional no están bien reflejadas las claves ajenas de las nuevas tablas que almacenan las probabilidades.

2021-05-13 15:01 UTC, infabeti commented on BDD-Reto4BigData/src/main/java/principal/Conexion.java
> +			System.out.println("Cerrada la conexion de prueba");
Porque, probais esto??? En un pull request solo mergeamos código definitivo

2021-05-13 15:02 UTC, infabeti requested changes
Mas allá del comentario que os he puesto, por mi parte está correcto

2021-05-13 16:30 UTC, Unai-GarciaGi commented on BDD-Reto4BigData/src/main/java/principal/Conexion.java
> +			System.out.println("Cerrada la conexion de prueba");
Ese trozo de código está para comprobar si la base de datos existe al lanzar la aplicación, como recomendaban en algunas páginas. Aún así, está borrado.

2021-05-14 08:24 UTC, Jose-Elorrieta approved these changes
De acuerdo. Ya veo correcto el esquema relacional. Os doy  mi visto bueno ¡ENHORABUENA!

2021-05-14 10:42 UTC, infabeti approved these changes

2021-05-14 10:42 UTC, merged